Add range limit option for `range` selection mode
NetWin/date-time-picker pull request #10
Opened 2024-11-07 14:18 UTC by IsabellaPap

:sparkles: :nail_care: 

## Changes

- add `rangeLimit` option to `date-time-inline`
- set `maxDate` dynamically to +`rangelimit` days when the first date is selected in `range` mode.

2024-11-07 14:44 UTC, NetWin requested changes
Awesome! Thank you. Would you mind adding the range limit to the ng-doc so we can display it's use/functionality there aswell? 😊

2024-11-07 14:44 UTC, NetWin commented on projects/picker/src/lib/date-time/date-time-inline.component.ts
> +   * */
```suggestion
   */
```

2024-11-07 14:50 UTC, IsabellaPap commented on projects/picker/src/lib/date-time/date-time-inline.component.ts
> +   * */
```suggestion
  /**
   * Limit to the amount of days that can be selected at once.
   * */
  @Input()
  public rangeLimit: number | null = null;

  /**
   * Variable to hold the old max date time value for when we override it with rangeLimit
   * */
  private _oldMaxDateTime: T | null;

  /**
   * Emits selected year in multi-year view
   * This doesn't imply a change on the selected date.
   * */
  @Output()
  yearSelected = new EventEmitter<T>();
```
All the other ones have 2 so maybe I should just add to the one on line 210?

2024-11-07 15:11 UTC, NetWin commented on projects/picker/src/lib/date-time/date-time-inline.component.ts
> +   * */
Yuck 🙈 
I'll note that down and fix it soon. Leave it as is then.

2024-11-07 15:44 UTC, NetWin approved these changes
Ignore my comment, ng-doc picked it up automagically 🪄 
Just played around with it a bit, Looks good to me 👍

2024-11-07 16:19 UTC, pawcoding commented on projects/picker/src/lib/date-time/date-time-inline.component.ts
> +  private _oldMaxDateTime: T | null;
I would maybe rename this to `_initialMaxDateTime`

2024-11-07 16:19 UTC, pawcoding commented on projects/picker/src/lib/date-time/date-time-inline.component.ts
> +
Also maybe add a comment here about what your new logic does. The whole component is already complex enough 😅

2024-11-08 10:48 UTC, NetWin approved these changes
🚀

2024-11-08 10:57 UTC, merged